### ISSUE TITLE
Separate guitar tracks?

### ISSUE THREAD

**Issue by skrivskithar** [sevagh/free-music-demixer#10]
First of all, thanks for this! I've been doing tabs for many years, and learned different ways to trying to separate tracks as best as possible, but this takes it to another level.

It would be nice to have the melody potentially separated by different guitar/keyboards/etc tracks. I hope this can be achieved eventually.

**Comment by sevagh** [comment]
I'm currently working on adding a new AI model that introduces 2 additional sources (guitar, piano). Stay tuned.

**Comment by sevagh** [comment]
Note that you can now get guitar + piano (which generally covers keyboard/synth sounds) stems using the Demucs 6-source model: 
![image](https://github.com/sevagh/free-music-demixer/assets/8574092/e34f17e3-6d3a-45c7-9a35-f2fb79900ee8)
