### ISSUE TITLE
CompileError: WebAssembly.instantiateStreaming(): Compiling function #21 failed: Wasm SIMD unsupported @+3930

### ISSUE THREAD

**Issue by joerg-pfruender** [sevagh/free-music-demixer#11]
Dear  @sevagh ,
 I wanted to "downlad weights" but it was aborted with the error message in javascript console:
```
CompileError: WebAssembly.instantiateStreaming(): Compiling function #21 failed: Wasm SIMD unsupported @+3930
```
I don't understand much of WASM. Could you please help?

My System: Firefox or Chromium
Ubuntu 22.04.3 LTS
AMD® Phenom(tm) ii x4 955 processor × 4

**Comment by sevagh** [comment]
OK nevermind - it's on purpose: https://github.com/sevagh/free-music-demixer/blob/main/CMakeLists.txt#L14C243-L14C243

Let me see how slow it is without the simd flag.

**Comment by sevagh** [comment]
I ended up deciding that I can only support SIMD for the implementation of Demucs. So, unfortunately, you'll need a way to use a different/newer browser
