### ISSUE TITLE
Errors in Safari 17.2.1 and Firefox 17.2.1 (developer edition)

### ISSUE THREAD

**Issue by animaux** [sevagh/free-music-demixer#16]
running macOS 14.2.1 and a MacBook Air M1

> Unhandled Promise Rejection: RuntimeError: Out of bounds memory access (evaluating '(_free=Module["_free"]=Module["asm"]["x"]).apply(null,arguments)')

<img width="1283" alt="Skjermbilde 2024-01-02 kl  21 11 07" src="https://github.com/sevagh/free-music-demixer/assets/446874/e8082b10-e94a-4a43-9068-1f8bdbc8ca0d">

This is from Safari, FF shows similar errors. File is not processed and no progress bar shows up. No errors in dev logs:

```
[Javascript 21:09:14] Fetched and cached model files
[Javascript 21:09:14] Selected model: demucs-6s
[Javascript 21:09:40] Initializing 4 workers!
[Javascript 21:09:41] Beginning demix job
[Javascript 21:10:35] Worker 2 is ready!
[Javascript 21:10:35] Worker 3 is ready!
[Javascript 21:10:35] Worker 0 is ready!
[Javascript 21:10:35] Worker 1 is ready!
```

**Comment by sevagh** [comment]
What action are you doing? The dev logs look like it's an individual track demix job. What kind of track is it? Can you maybe try with 4 GB (1 worker)?

**Comment by animaux** [comment]
Right. It’s an individual track. File is MP3, 2,2MB. 1:49 min. 44,1kHz. Stereo. 160kbit/s. Actually the track is just synth and drums. Could that be a problem?

I tried all of the memory options available as well as both of the models (4 and 6 stems).

**Comment by animaux** [comment]
Just tried a different track, 4GB. Same error showed up straight away.

**Comment by sevagh** [comment]
Can you copy/pasted the text of those firefox/safari developer logs so I can do some research

**Comment by animaux** [comment]
Sure, this is FF122.0b4 single short MP3 file, single Worker:

```
Service worker installing [main.js:10:17](https://freemusicdemixer.com/main.js)
Setting bannerDismissed to true [main.js:952:13](https://freemusicdemixer.com/main.js)
true [main.js:955:13](https://freemusicdemixer.com/main.js)
Loading wasm module for model demucs-6s [worker.js:37:21](https://freemusicdemixer.com/worker.js)
Loaded model binary data, now mounting to WASM VFS [worker.js:43:25](https://freemusicdemixer.com/worker.js)
RuntimeError: index out of bounds [demucs.wasm:171459:1](https://freemusicdemixer.com/demucs.wasm)
```

**Comment by animaux** [comment]
Similar output with 2 workers.

**Comment by animaux** [comment]
In Safari 17.2.1 it’s like in the screenshot above:

```
[Error] FetchEvent.respondWith received an error: TypeError: Load failed
[Error] Cannot load https://www.googletagmanager.com/gtag/js?id=G-B0BF5H94FM.
[Error] Failed to load resource: FetchEvent.respondWith received an error: TypeError: Load failed (js, line 0)
[Log] Service worker active (main.js, line 14)
[Log] Loading wasm module for model demucs-6s (worker.js, line 37)
[Log] Loaded model binary data, now mounting to WASM VFS (worker.js, line 43)
[Error] Unhandled Promise Rejection: RuntimeError: Out of bounds memory access (evaluating '(_free=Module["_free"]=Module["asm"]["x"]).apply(null,arguments)')
	<?>.wasm-function[173] (demucs.js:9:74503)
	<?>.wasm-function[27]
	<?>.wasm-function[586]
	586
	(anonym funksjon) (demucs.js:9:74503)
	processAudio (worker.js:171)
	(anonym funksjon) (worker.js:53)
```

Does not seem to be any different with different files.

**Comment by sevagh** [comment]
Is there anything printed in the right column of the dev logs? With prefix `[WASM/C++`

**Comment by animaux** [comment]
> Is there anything printed in the right column of the dev logs? With prefix `[WASM/C++`

I’m afraid not.

**Comment by sevagh** [comment]
On both your tested browsers, can you show what features are checked/unchecked on this site? https://wasm-feature-detect.surma.technology/ 

E.g. for me on Firefox 121 right now:

<h1>Your browser supports:</h1>
  
✔️ | bigInt
-- | --
✔️ | bulkMemory
✔️ | exceptions
✔️ | extendedConst
✔️ | gc
❌ | jspi
❌ | memory64
❌ | multiMemory
✔️ | multiValue
✔️ | mutableGlobals
✔️ | referenceTypes
❌ | relaxedSimd
✔️ | saturatedFloatToInt
✔️ | signExtensions
✔️ | simd
✔️ | streamingCompilation
✔️ | tailCall
❌ | threads
❌ | typeReflection

**Comment by animaux** [comment]
## Safari 17.2.1

✔️ | bigInt
✔️ | bulkMemory
✔️ | exceptions
❌ | extendedConst
❌ | gc
❌ | jspi
❌ | memory64
❌ | multiMemory
✔️ | multiValue
✔️ | mutableGlobals
✔️ | referenceTypes
❌ | relaxedSimd
✔️ | saturatedFloatToInt
✔️ | signExtensions
✔️ | simd
✔️ | streamingCompilation
❌ | tailCall
❌ | threads
❌ | typeReflection


## Firefox 122.0b4 (developer edition)

✔️ | bigInt
✔️ | bulkMemory
✔️ | exceptions
✔️ | extendedConst
✔️ | gc
❌ | jspi
❌ | memory64
❌ | multiMemory
✔️ | multiValue
✔️ | mutableGlobals
✔️ | referenceTypes
❌ | relaxedSimd
✔️ | saturatedFloatToInt
✔️ | signExtensions
✔️ | simd
✔️ | streamingCompilation
✔️ | tailCall
❌ | threads
❌ | typeReflection

**Comment by sevagh** [comment]
How much total memory does your macbook air have?

**Comment by animaux** [comment]
16 GB

**Comment by sevagh** [comment]
I'm definitely interested in solving this problem for you but I'm just shooting in the dark. I'm not very good as OSX but I have access to an M1 Macbook Pro with 32GB of RAM, Safari 17.1 and Firefox 121 where everything "just works(TM)".

If you're open to chatting on Discord (or some other platform) so we can try different things back-and-forth, I'm down for that. Otherwise, another option I have is to create some special debug version of the binary that prints extra information to put on the staging site (lab.freemusicdemixer.com), and have you run those to dump extra information

I see the logs always mention the Demucs 6-source model. Have you tried with the 4-source model?

**Comment by animaux** [comment]
Many thanks. I didn’t expect this could be a problem in 2024 but — I did a restart of the system and tried again: and it works now `:D`. I have no idea what could have caused the problems in *any* browser. `¯\_(ツ)_/¯`

**Comment by sevagh** [comment]
:crystal_ball: computers

**Comment by animaux** [comment]
Thanks for you patience! `:)`
