### ISSUE TITLE
Model producing garbage outputs?

### ISSUE THREAD

**Issue by joshbarrass** [sevagh/free-music-demixer#4]
For some reason, the only result I'm getting (at least for the file I've tried) is just [garbage noise](https://voca.ro/15R3VNkXWOHz). I'm not sure if there's anything I'm doing wrong in terms of the format I'm uploading (I've tried 24-bit FLAC and 16-bit WAV, both to no avail) or whether it's just a song that doesn't work well, but something clearly isn't working right for this song.

If there are any other details I can provide that might help with debugging this, please let me know.

**Comment by joshbarrass** [comment]
I just tried opening the output file in Audacity to take a look at it and it behaves really strangely. When playing it, Audacity will skip ahead up to around 30s at a time. Is the WAV output perhaps malformed?

**Comment by joshbarrass** [comment]
Nevermind, I just tried it for a different song and it worked well enough. I'm guessing the model just doesn't agree with that particular song.

**Comment by sevagh** [comment]
@joshbarrass I'm still interested in debugging this - you could email me the tracks that are failing so I can upload them while I debug locally.

**Comment by sevagh** [comment]
You could maybe try to use the real Python model: https://github.com/sigsep/open-unmix-pytorch#-getting-started 

```
docker run -v ~/Music/:/data -it faroit/open-unmix-pytorch "/data/track1.wav" --outdir /data/track1
```
If that also sounds like the same garbage, then it's an interesting edge case in the neural network.
If that sounds correct, then it's a problem with my website implementation specifically.

**Comment by joshbarrass** [comment]
Hi @sevagh. I'll give the original Python model a go and report back with results.

**Comment by joshbarrass** [comment]
It seems to work fine with the original model, so I guess this points towards it being an implementation problem. I'll reopen my issue.

Based on the weird playback behaviour I observed in Audacity, my gut feeling is that the site produced a malformed WAV somehow. I'll send you an email with a bunch of the relevant files for you to investigate.

**Comment by sevagh** [comment]
Great, I received the files, set up the test bench, and I can reproduce the bug.

**Comment by sevagh** [comment]
NaN outputs indeed:
```
[WASM/C++ 10:38:24] Getting waveforms from istft
[WASM/C++ 10:38:25] printing min, max values of target_waveforms: 
[WASM/C++ 10:38:25] target: 0
[WASM/C++ 10:38:25] target_waveforms[target].minCoeff(): nan
[WASM/C++ 10:38:25] target_waveforms[target].maxCoeff(): -nan
[WASM/C++ 10:38:25] target: 1
[WASM/C++ 10:38:25] target_waveforms[target].minCoeff(): nan
[WASM/C++ 10:38:25] target_waveforms[target].maxCoeff(): -nan
[WASM/C++ 10:38:25] target: 2
[WASM/C++ 10:38:25] target_waveforms[target].minCoeff(): nan
[WASM/C++ 10:38:25] target_waveforms[target].maxCoeff(): -nan
[WASM/C++ 10:38:25] target: 3
[WASM/C++ 10:38:25] target_waveforms[target].minCoeff(): nan
[WASM/C++ 10:38:25] target_waveforms[target].maxCoeff(): -nan
```
Now, if I disable the post-neural network filtering step (Wiener filtering), the output quality is pretty decent:
```
```
There must be a division by 0 somewhere in the Wiener filtering, I suspect because there are no drums, and there's a division with 0-valued drum estimate somewhere - and I'm probably missing an epsilon term or something that has been accounted for in the Python code.

**Comment by joshbarrass** [comment]
Glad you could reproduce it and seem to have an idea of where the problem is coming from. Do you know if the same bug affects [umx.cpp](https://github.com/sevagh/umx.cpp) as well?

**Comment by sevagh** [comment]
Huh, that's an excellent point actually. Umx.cpp does _not_ have the bug.

As for the relationship between umx.cpp and free-music-demixer, they're supposed to have "parity", but this time around I got sloppy:
1. I implemented a very basic form of Wiener filtering with my own "Tensor" class (using nested std::vector)
2. I pushed this to umx.cpp, happy that I finally got Wiener filtering working
3. I copied the initial Wiener code to free-music-demixer
4. There I learned that I was running into the 4GB memory limit so I changed up the Wiener code entirely
5. Testing on typical tracks showed the results to be identical, but this edge case works in umx.cpp and fails in free-music-demixer

So right now free-music-demixer has buggier but more efficient, Eigen-based Wiener filtering code, while umx.cpp has a naive Wiener filtering that doesn't have the same bug.

**Comment by sevagh** [comment]
I believe I found the bug: https://github.com/sevagh/free-music-demixer/blob/main/src/wiener.cpp#L159 

By default, Eigen tensors are not initialized to 0, but some random value. The fix was to set the tensor to zero before filling the diagonal with epsilon:
```
(system) sevagh@pop-os:~/repos/free-music-demixer$ git --no-pager diff src/wiener.cpp
diff --git a/src/wiener.cpp b/src/wiener.cpp
index e4c946b..1be77ab 100644
--- a/src/wiener.cpp
+++ b/src/wiener.cpp
@@ -157,6 +157,8 @@ std::array<Eigen::Tensor3dXcf, 4> umxcpp::wiener_filter(
     std::cout << "Wiener-EM: Initialize tensors" << std::endl;

     Eigen::Tensor2dXcf regularization(nb_channels, nb_channels);
+    // first set to zero
+    regularization.setZero();
     // Fill the diagonal with sqrt(eps)
     fill_diagonal(regularization, std::sqrt(eps));
```
Release forthcoming.

**Comment by sevagh** [comment]
Fixed version is live on the website. I'm now testing your input clip on the live site: https://freemusicdemixer.com/ 

You can go ahead retest whenever and close the issue if it sounds fixed to you (it sounds fixed to me).

**Comment by joshbarrass** [comment]
I agree it sounds fixed :) Thanks for looking into this!
