### ISSUE TITLE
Separate vocals mixed

### ISSUE THREAD

**Issue by tic13** [sevagh/free-music-demixer#6]
Hi,i have a old capture record from TV in the 90, was record in a one of the first  dual audio vcr of the epoque, so they save in the tape the original track in v.o+dubbed track. Unfortunly these vcr uses a fine separation line  in the tape to separate the audio Channels, and the tape get this line  deteriorated over the years, so today the vcr can't separate the audio and read the the two audio tracks at the same time, resulting in a audio track with the v.o+dubbed track playing at the same time.

My questions is if with the help of a Ia can be possible isolate and separate these audio voice  tracks to their normal state.

**Comment by sevagh** [comment]
This is a tricky question. The model used in this website is older and cannot do very complicated tasks like separating one voice from another voice - it can only treat "all vocals" as one type of isolation.

There are more sophisticated softwares available, like this one: https://ultimatevocalremover.com/

Or maybe you can ask in a specialist forum about advice for your specific use case e.g. https://audiosex.pro/forums/software.76/

**Comment by sevagh** [comment]
Closing as not super related to the specific stem demixing AI models provided by this site; good luck!
